### ISSUE TITLE
New

### ISSUE THREAD

**Issue by Danilwsk** [WeekThor/AdminProtect#3]
Create a new plugin on gm
/gm 0 - survival
/gm 1 - creative
/gm 2 - adventures
/gm 3 - spectator
with permission to use it.
with permission to issue gm.
And the ability to change the description

**Comment by Danilwsk** [comment]
I'll be waiting please

**Comment by WeekThor** [comment]
I had plans to add something like this to AdminProtect (preventing from giving gamemode to other players) but it is not a primary task. Possibly in future updates...

**Comment by Danilwsk** [comment]
Can you add clearchat? With a message in the chat

**Comment by WeekThor** [comment]
I'll think about it, but not in the coming 2.0.0 release. Maybe in the next beta-versions after it.

Thanks for the suggestion

**Comment by Danilwsk** [comment]
Так к плагину AdminProtect. Вы можете добавить сообщение в чат для забаненных типо "Если вы не согласны с наказанием, обратитесь на форум." То есть это не причина , это текст , который всегда будет появляться  после причины наказания

**Comment by Danilwsk** [comment]
So to the AdminProtect plugin. You can add a message to the chat for banned people like "If you do not agree with the punishment, contact the forum." That is , it is not a reason , it is a text that will always appear after the reason for the punishment

**Comment by WeekThor** [comment]
Messages can be edited in config.yml
```YAML
TempBannedPlayerKickMessage: "You was banned on this server until %duration%.\n Reason: %reason% (%sender%§r)\n\n If you do not agree with the punishment, contact the forum."
BannedPlayerKickMessage:     "You was banned on this server.\n Reason: %reason% (%sender%§r)\n\n If you do not agree with the punishment, contact the forum."
BannedIPKickMessage:     "Your IP was blocked on this server.\n Reason: %reason% (%sender%§r)\n\n If you do not agree with the punishment, contact the forum."
TempBannedIPKickMessage: "Your IP was blocked on this server until %duration%.\n Reason: %reason% (%sender%§r)\n\n If you do not agree with the punishment, contact the forum."
```
where `\n` is new line, `%sender%` is admin name. 
But it was broken after updating to pmmp 4.0.0 and I fixed it just now (fixed version was not uploaded in Releases tab)😁😁😁
